CREATE TEMPORARY TABLE students (id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(30) NOT NULL, score INTEGER CHECK (score BETWEEN 0 AND 100));
INSERT INTO students (name, score) VALUES ('Mina', 80), ('Jin', 60);
SELECT * FROM students ORDER BY id;
